;==================================================================================================
; Metadata.inc
;
; This file defines the global Metadata settings.
;

;------------------------------------------------------------------------------
;
[Metadata]
;
Name=Trail
Author=Lokdora
Version=0.1
License=Creative Commons Zero v1.0 Universal
Information=Source: https://github.com/Dorapower/Trail
